config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stm.urls', namespace='stm')),
]

stm/urls.py
from django.urls import path
from .views import Signup, HomeView, Login, MemoryCreateView, MemoryEditView
from django.contrib.auth.views import LogoutView

app_name = 'stm'
urlpatterns = [
    path("signup/", Signup.as_view(), name="signup"),
    path("", HomeView.as_view(), name="home"),
    path("login/", Login.as_view(), name="login"),
    path("logout/", LogoutView.as_view(template_name="stm/home.html"), name="logout"),
    path("create/", MemoryCreateView.as_view(), name="create"),
    path("edit/<pk>", MemoryEditView.as_view(), name="edit"),
]

stm/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

class ThoughtsQuerySet(models.QuerySet):
    def mine(self, pk):
        return self.filter(user=pk)
    def others(self, pk):
        return self.exclude(user=pk)


class memory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    # title = models.CharField(_("A Phrase for my thought"), max_length=50, blank=False)
    thought = models.TextField(_("All I can think of my thought"))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # thoughts = ThoughtsQuerySet.as_manager()

stm/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate
from django import forms
from .models import memory
import string
from django.utils.translation import ugettext_lazy as _

class UserSignupForm(UserCreationForm):

    def clean_username(self):
        username = self.cleaned_data["username"]
        if get_user_model().objects.filter(username__iexact=username).exists():
            print("user exist")
            raise forms.ValidationError("username taken, try another...")
        return username


class UserLoginForm(AuthenticationForm):

    error_messages = {
        'invalid_login': _(
            "Please enter a correct %(username)s and password. Password is case-sensitive"
        ),
        'inactive': _("This account is inactive."),
    }

    def clean_username(self):
        username = self.cleaned_data["username"]
        _user = get_user_model().objects.filter(username__iexact=username)
        if _user.exists():
        #since our signup form is designed to store case insensitive username,
        #only one user will be returned by the filter. we can index with [0]
            username = _user.first().username
        return username

class MemoryEditForm(forms.ModelForm):
    
    class Meta:
        model = memory
        fields = ("thought", )

    # def clean_thought

stm/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic import CreateView, ListView, UpdateView
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import UserSignupForm, UserLoginForm
from .models import memory
from django.contrib.auth.views import LoginView, PasswordChangeView


class Signup(CreateView):
    form_class = UserSignupForm
    template_name = 'stm/signup.html'

    def post(self, request, *args, **kwargs):
        signup = self.form_class(request.POST)
        if signup.is_valid():
            username = signup.cleaned_data['username']
            password = signup.cleaned_data["password1"]
            signup.save()
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('stm:home')
        return render(request, self.template_name, {'form': self.form_class(request.POST)})


class Login(LoginView):
    form_class = UserLoginForm
    template_name = "stm/login.html"
    redirect_field_name = "stm:home"


class HomeView(ListView):
    context_object_name = 'thoughts'
    model = memory
    template_name = 'stm/home.html'

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class MemoryCreateView(LoginRequiredMixin, CreateView):
    model = memory
    template_name = "stm/create.html"
    fields = ('thought',)
    login_url = "stm:login"
    success_url = "stm:home"

    def post(self, request, *args, **kwargs):
        """
        Handle POST requests: instantiate a form instance with the passed
        POST variables and then check if it's valid.
        """
        form = self.get_form()
        if form.is_valid():
            form_object = form.save(commit=False)
            form_object.user_id = get_user_model().objects.get(username=request.user).id
            form.save()
            return redirect(self.success_url)
        else:
            return self.form_invalid(form)

class MemoryEditView(LoginRequiredMixin, UpdateView):
    model = memory
    template_name = "stm/update.html"
    fields = ('thought',)
    success_url = "stm:home"
    # login_url = "stm:login"

templates/stm/create.html
<a href="{% url 'stm:home' %}"> <--Go back </a>

{% if form %}
<form method="post">
{% csrf_token %}
{{form.as_p}}
<button type="submit">Submit</button>
<button type="reset">Reset</button>
</form>

{% endif %}

templates/stm/home.html
{% if not request.user.is_authenticated %}
    <a href="{% url 'stm:signup' %}">Signup</a>
    <a href="{% url 'stm:login' %}">Login</a>

{% else %}
    <h2>Welcome {{request.user}}</h1>
    {% if thoughts %}
        {% for thought in thoughts %}
        <p>{{thought.thought}} at {{thought.created_at|time:""}} <button>thinking alike</button><br>
            {% if request.user == thought.user %}
                <a href="{% url 'stm:edit' thought.id %}"> Edit </a>
            {% endif %}
        </p>
        {% endfor %}
        {% else %}
        <strong> Your mind is clean! </strong>
    {% endif %}
<br>
<a href="{% url 'stm:create' %}">Add thought</a>
<a href="{% url 'stm:logout' %}">Logout</a>
{% endif %}

templates/stm/login.html
{% if form %}

<form method="post">
{% csrf_token %}
{{form.as_p}}
<button type="submit">Login</button>
</form>
{% endif %}

<a href="{% url 'stm:signup' %}">Signup</a>

templates/stm/signup.html
{% if form %}
<a href="{% url 'stm:login' %}">Login</a>
<form method="post">
{% csrf_token %}
{% for formm in form %}
<!-- <p>{{formm.id_for_label}}</p> -->
<p>{{formm.label}} {{formm}}</p>
</p>{{formm.errors}}</p>
{% comment %} {{formm.help_text}} {% endcomment %}

{% endfor %}
<button type="submit">SignUp</button>
</form>
{% endif %}
{{request.messages}}

templates/stm/update.html
<a href="{% url 'stm:home' %}"> <--Go back </a>

{% if form %}
<form method="post">
{% csrf_token %}
{{form.as_p}}
<button type="submit">Update</button>
<button type="reset">Reset</button>
</form>

{% endif %}